{% set name = "entrypoint2" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/entrypoint2-{{ version }}.tar.gz
  sha256: 67e906f6ad958d83f48b4edec28d7dd82670e9261988f6b4a6b63abc9fb3be56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - entrypoint2
    - entrypoint2.examples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ponty/entrypoint2
  summary: easy to use command-line interface for python modules
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
