{% set name = "entrypoint2" %}
{% set version = "1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/entrypoint2-{{ version }}.tar.gz
  sha256: fc0b7fe7b21acdab47a585ab9407ca7e5c4f96cb6888575db6b0ceb91f0e105a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - entrypoint2
    - entrypoint2.examples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ponty/entrypoint2
  summary: easy to use command-line interface for python modules
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
